---
- name: Copy systemd template
  template:
    src: "templates/elasticsearch.service.j2"
    dest: "/etc/systemd/system/elasticsearch.service"

- name: Re/Start Elasticsearch
  service:
    name: "elasticsearch.service"
    state: restarted
    daemon_reload: yes
    enabled: yes
